name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
template: |
    # What's Changed

    $CHANGES
categories:
  - title: 🙌 Enhancements
    label: is:enhancement
  - title: 🐛 Bug Fixes
    label: is:bug

